### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by trphp** [39ff/ultimatetwitter#2]
I didn't run the system, can you help me?
Or if there is a problem, would you please update it?

**Comment by 39ff** [comment]
what error ?

**Comment by trphp** [comment]
twitter favorites create

**Comment by trphp** [comment]
how can I do
How do I verify recaptcha on login automatically

**Comment by 39ff** [comment]
i think recaptcha is not appear in twitter except account lock page.

**Comment by trphp** [comment]
how do i like it on twitter ?

**Comment by trphp** [comment]
What do I need to do to get likes?

**Comment by trphp** [comment]
are you here ?

**Comment by 39ff** [comment]
please use https://github.com/mpyw/cowitter
